version: "3"
services:
  nginx: # 服务名称，用户自定义
    image: nginx:latest  # 镜像版本
    ports:
      - 80:80  # 暴露端口
    volumes: # 挂载
      - /d/docker/nginx/html:/usr/share/nginx/html
      - /d/docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    privileged: true # 这个必须要，解决nginx的文件调用的权限问题

  hospital:
    image: hospital:latest
    #network_mode: "host"
    build: . # 表示以当前目录下的Dockerfile开始构建镜像
    ports:
      - 8081:8081
    depends_on:
      - mysql

  mysql:
    restart: always
    ports:
      - 3306:3306
    image: mysql:8.0
    container_name: my_mysql
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
      --explicit_defaults_for_timestamp=true
    privileged: true
      #--lower_case_table_names=1
    #network_mode: "host"
#
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 123456!@#
      MYSQL_DATABASE: hospital
    volumes:
      - ./mysql/mydir:/mydir
      - ./mysql/datadir:/var/lib/mysql
      - ./mysql/schema:/docker-entrypoint-initdb.d/
      - ./mysql/conf/my.cnf:/etc/my.cnf



  redis:
    image: redis:latest



